name: flutter_sample_splash
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_native_splash:
  color: '#add8e6'

  # Android11 アスペクト比が維持されない
  # Android12 非対応
  # iOS アスペクト比が維持されない
#  background_image: 'assets/images/background.png'

  # android
  # original=1600, 4000
  # xxxhdpi =1600, 4000
  # xxhdpi  =1200, 3000
  # xhdpi   = 800, 2000
  # hdpi    = 600, 1500
  # mdpi    = 400, 1000
  # 縦横サイズが大きすぎると、画面をはみ出てしまうのでサイズは注意が必要
  # 1200が良い感じ
  image: 'assets/images/splash.png'

  # ダークモードには対応する
  color_dark: '#262626'
  image_dark: 'assets/images/splash.png'

  # Android12以上はAndroidOS側でアプリアイコンをスプラッシュ表示してしまうので以下の通り設定が必要
  #  指定がないと、代わりにアプリ起動アイコンが使用される
  #  画面中央の円型に切り取られる。
  #  背景付き画像の場合、960x960pxで、直径640pxの円の中に収まる必要がある
  #  背景なし画像の場合、1152x1152pxで、直径768pxの円の中に収まる必要がある
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/images/splash_android12.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/splash_android12.png'

  # ブランディング
  # Android12は動かないはずだが動いた
#  branding: 'assets/images/branding.png'
#  branding_dark: 'assets/images/branding.png'
#  branding_mode: bottom

  # android_gravityはAndroid12から効かなくなってる（Android11以下まで）
#  android_gravity: bottom
#  android_gravity: center
#  android_gravity: center_horizontal
#  android_gravity: center_vertical
#  android_gravity: clip_horizontal
#  android_gravity: clip_vertical
#  android_gravity: end
#  android_gravity: fill
#  android_gravity: fill_horizontal
#  android_gravity: fill_vertical
#  android_gravity: left
#  android_gravity: right
#  android_gravity: start
#  android_gravity: top

#  ios_content_mode: scaleToFill # できた アスペクト比を保たず全画面表示
#  ios_content_mode: scaleAspectFit #できた アスペクト比を保って横幅いっぱいに表示
#  ios_content_mode: scaleAspectFill # できた アスペクト比をたもって全画面表示（周りが切り取られる）
#  ios_content_mode: center #できた センター表示 デフォルト
#  ios_content_mode: top #できた
#  ios_content_mode: bottom #できた
#  ios_content_mode: left #できた
#  ios_content_mode: right #できた
#  ios_content_mode: topLeft # おかしい、拡大表示された
#  ios_content_mode: topRight #できた
#  ios_content_mode: bottomLeft #できた
#  ios_content_mode: bottomRight #できた

#  web_image_mode: center # デフォルト
#  web_image_mode: contain # できた　scaleAspectFit　と同じ
#  web_image_mode: stretch # できた scaleAspectFillと同じ
#  web_image_mode: cover # できた

  # デフォルトは false
  # webでは動作しない（NotificationBarが無いので）
  #Androidとは異なり、iOSはアプリの読み込み時に通知バーを自動的に表示しません。
  #通知バーを表示するには、Flutterアプリに次のコードを追加します。
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  # iOS ちゃんと動いた
  # Android 11 ちゃんと動いた
  # Android 12 動かない
  fullscreen: true
